EventHub/mysite/custom_app/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='chat'
    ),
]

EventHub/mysite/eventhub/urls.py
from django.contrib import admin
from django.urls import path, include
from news import views
from custom_app import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("news.urls")),
    path('privatechat', include('django_private_chat.urls')),
    path('chat', include('custom_app.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ]

EventHub/mysite/news/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static



app_name = "news"
urlpatterns = [
    path('', views.home, name='home'),
    path('map', views.map, name='map'),
    path("logout/", views.logout_request, name="logout"),
    path('loginform/', views.loginform, name='loginform'),
    path('signupform/', views.signupform, name='signupform'),
    path('userhome/',views.userhome,name="userhome"),
    path('usermap/',views.usermap,name="usermap"),
    path('chat/',include('custom_app.urls')),
    path('analysis/',views.analysis,name="analysis"),
    path('report/',views.report,name="report"),


]

EventHub/mysite/custom_app/models.py
from django.db import models

# Create your models here.

EventHub/mysite/news/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils import timezone
from django_random_queryset import RandomManager

# Create your models here.

 
class location(models.Model):
    objects=RandomManager()

    country = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    lat = models.FloatField(max_length=100)
    lon = models.FloatField(max_length=100)
    text = models.CharField(max_length=500, null=True)
    event = models.CharField(max_length=20, null=True)

EventHub/mysite/news/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


#added comment
class NewUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms. EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

EventHub/mysite/custom_app/views.py
from braces.views import LoginRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model


class UserListView(LoginRequiredMixin, generic.ListView):
    model = get_user_model()
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = 'custom_app/chat.html'
    login_url = 'admin/'

EventHub/mysite/news/templates/news/analysis.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/icon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Event-Hub</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
    <script type='text/javascript' src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/now-ui-dashboard.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="orange">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text logo-mini">
                    <i class="far fa-clock"></i>
                </a>
                <a href="http://www.creative-tim.com" class="simple-text logo-normal">
                    Welcome {{user.username}}
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="active">
                        <a href="{% url 'news:userhome' %}">
                            <i class="now-ui-icons design_app"></i>
                            <p>TWEETS & NEWS</p>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'news:map' %}">
                            <i class="now-ui-icons users_single-02"></i>
                            <p>MAP</p>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'news:analysis' %}">
                            <i class="now-ui-icons education_atom"></i>
                            <p>ANALYSIS</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'news:report' %}">
                            <i class="now-ui-icons location_map-big"></i>
                            <p>REPORTS</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'chat' %}">
                            <i class="now-ui-icons ui-1_bell-53"></i>
                            <p>CHATS</p>
                        </a>
                    </li>
                    <li>
                        <a href="/logout">
                            <i class="now-ui-icons design_bullet-list-67"></i>
                            <p>LOGOUT</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!--
            <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute bg-primary fixed-top">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a class="navbar-brand" href="#pablo">Dashboard</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <form>
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                                </span>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <i class="now-ui-icons media-2_sound-wave"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Stats</span>
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="now-ui-icons location_world"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Some Actions</span>
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <i class="now-ui-icons users_single-02"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Account</span>
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            -->
            <div style="height:62px; background-color:#ffff;">

                <h3>Event Detection</h3>

            </div>
            <br>
            <br>
            <div>
              
              <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Diesease</h5>
                    <h3 class="mb-1" style="color:red;">{{c1}}</h3>
                  </div>
                </a>
                {% for i in tw1 %}
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                        <p class="mb-1">{{i.text}}</p>
                    </a>
                {% endfor %}
              </div>

              <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">election</h5>
                    <h3 class="mb-1" style="color:red;">{{c2}}</h3>
                  </div>
                </a>
                {% for i in tw2 %}
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                        <p class="mb-1">{{i.text}}</p>
                    </a>
                {% endfor %}
              </div>

              <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">football</h5>
                    <h3 class="mb-1" style="color:red;">{{c3}}</h3>
                  </div>
                </a>
                {% for i in tw3 %}
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                        <p class="mb-1">{{i.text}}</p>
                    </a>
                {% endfor %}
              </div>
                  
            </div><!-- End Contact Section -->



        </div>
    </div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/core/popper.min.js' %}"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'assets/js/now-ui-dashboard.js' %}"></script>
<!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/demo/demo.js' %}"></script>
<script>
    $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();
    });
</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
    var config = {
      type: 'pie',
      data: {datasets: [{data: {{data|safe }},backgroundColor: ['#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'],label: 'text'}],labels: {{ labels|safe }}},options: {responsive: true}};

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

</script>

</html>

EventHub/mysite/news/templates/news/entry.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
  	<title>EventHub</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'login/images/icons/icon.png' %}"/>

    <!--Map files-->
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
    <script type='text/javascript' src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Favicons -->
    <link href="{% static 'assets/img/icon.png' %}" rel="icon">
    <link href="{% static 'assets/img/icon.png' %}" rel="apple-touch-icon">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

    <!--original files-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static 'navbar/css/style.css' %}">
  </head>
  <body>
    {% include "news/includes/messages.html" %}
    <div class="wrapper d-flex align-items-stretch">
        {% include "news/includes/navbar.html" %}


        {% block content %}
        {% endblock %}
    </div>
    <!--map files-->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/vendor/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendor/typed.js/typed.min.js' %}"></script>
    <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>


    <script src="{% static 'navbar/js/jquery.min.js' %}"></script>
    <script src="{% static 'navbar/js/popper.js' %}"></script>
    <script src="{% static 'navbar/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'navbar/js/main.js' %}"></script>
  </body>
</html>

EventHub/mysite/news/templates/news/loginform.html
{% extends "news/login.html" %}
{% load static %}
{% block content %}
    <form class="login100-form validate-form flex-sb flex-w" method="POST">
        {% csrf_token %}

        <span class="login100-form-title p-b-20">
            <P style="font-size:40px; color:rgb(108, 8, 117);">LOGIN</P>
        </span>
        
        <a href="#" class="btn-face m-b-20">
            <i class="fa fa-facebook-official"></i>
            Facebook
        </a>

        <a href="#" class="btn-google m-b-20">
            <img src="{% static 'login/images/icons/icon-google.png' %}" alt="GOOGLE">
            Google
        </a>
        
        <div class="p-t-31 p-b-9">
            <label for="{{ form.username.id_for_label }}"><span class="txt1">Username</span></label>
        </div>
        <div class="wrap-input100 validate-input">
            {{form.username}}
            <span class="focus-input100"></span>
        </div>
        <div class="p-t-13 p-b-9">
            <label for="{{ form.password.id_for_label }}"><span class="txt1">password:</span></label>
        </div>
        <div class="wrap-input100 validate-input">
            {{form.password}}
            <span class="focus-input100"></span>
        </div>
        
        
        <div class="container-login100-form-btn m-t-17">
            <button class="login100-form-btn" type="submit">
                Sign In
            </button>
        </div>
        <div class="w-full text-center p-t-10">
            <div style="text-align: center;">
                Not a member?<a href="{% url 'news:signupform' %}">
                 Sign up now
                </a><br/>
            </div> &nbsp;
            <div style="text-align: center;">
                Return To<a href="{% url 'news:home' %}">
                  Home
                 </a>
            </div>
        </div>
    </form>
{% endblock %}

EventHub/mysite/news/templates/news/signupform.html
{% extends "news/signup.html" %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h3>New Account?</h3>
      
        {{form.as_p}}
        

        <button class="btn" style="background-color:skyblue; color:blue" type="submit">Register</button> &emsp;
        <div style="text-align: center;">
            Already a member?<a href="{% url 'news:loginform' %}">
                Sign in now
            </a>
        </div> &nbsp;
        <div style="text-align: center;">
            Return To<a href="{% url 'news:home' %}">
                Home
            
            </a>
        </div>
    </form>
    
{% endblock %}

EventHub/mysite/news/templates/news/userhome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/icon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Event-Hub</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
    <script type='text/javascript' src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/now-ui-dashboard.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="orange">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text logo-mini">
                    <i class="far fa-clock"></i>
                </a>
                <a href="http://www.creative-tim.com" class="simple-text logo-normal">
                    Welcome {{user.username}}
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="active">
                        <a href="{% url 'news:userhome' %}">
                            <i class="now-ui-icons design_app"></i>
                            <p>TWEETS & NEWS</p>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'news:map' %}">
                            <i class="now-ui-icons users_single-02"></i>
                            <p>MAP</p>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'news:analysis' %}">
                            <i class="now-ui-icons education_atom"></i>
                            <p>ANALYSIS</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'news:report' %}">
                            <i class="now-ui-icons location_map-big"></i>
                            <p>REPORTS</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'chat' %}">
                            <i class="now-ui-icons ui-1_bell-53"></i>
                            <p>CHATS</p>
                        </a>
                    </li>
                    <li>
                        <a href="/logout">
                            <i class="now-ui-icons design_bullet-list-67"></i>
                            <p>LOGOUT</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!--
            <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute bg-primary fixed-top">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a class="navbar-brand" href="#pablo">Dashboard</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <form>
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                                </span>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <i class="now-ui-icons media-2_sound-wave"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Stats</span>
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="now-ui-icons location_world"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Some Actions</span>
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <i class="now-ui-icons users_single-02"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Account</span>
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            -->
            <div style="height:62px; background-color:#ffff;">

                <marquee style="padding-top:15px; padding-bottom:20px; font-weight:bold; color:rgb(238, 14, 14);">!!! Latest Tweets and Newses !!!</marquee>

            </div>
            <section class="paralax-mfs footer-paralaxs bg-image route" >
             {% for tweet in public_tweets %}
                <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                 <div class="card-header">Tweets</div>
                    <div class="card-body">
                      <h5 class="card-title">Info card title</h5>
                      <p class="card-text">{{ tweet.text }}</p>
                    </div>
                </div>

             {% endfor %}
            </section><!-- End Contact Section -->



        </div>
    </div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/core/popper.min.js' %}"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'assets/js/now-ui-dashboard.js' %}"></script>
<!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/demo/demo.js' %}"></script>
<script>
    $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();
    });
</script>

</html>