EventHub/mysite/custom_app/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='chat'
    ),
]

EventHub/mysite/eventhub/urls.py
from django.contrib import admin
from django.urls import path, include
from news import views
from custom_app import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("news.urls")),
    path('privatechat', include('django_private_chat.urls')),
    path('chat', include('custom_app.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ]

EventHub/mysite/news/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static



app_name = "news"
urlpatterns = [
    path('', views.home, name='home'),
    path('map', views.map, name='map'),
    path("logout/", views.logout_request, name="logout"),
    path('loginform/', views.loginform, name='loginform'),
    path('signupform/', views.signupform, name='signupform'),
    path('userhome/',views.userhome,name="userhome"),
    path('usermap/',views.usermap,name="usermap"),
    path('chat/',include('custom_app.urls')),
    path('analysis/',views.analysis,name="analysis"),
    path('report/',views.report,name="report"),


]

EventHub/mysite/custom_app/models.py
from django.db import models

# Create your models here.

EventHub/mysite/news/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils import timezone
from django_random_queryset import RandomManager

# Create your models here.

 
class location(models.Model):
    objects=RandomManager()

    country = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    lat = models.FloatField(max_length=100)
    lon = models.FloatField(max_length=100)
    text = models.CharField(max_length=500, null=True)
    event = models.CharField(max_length=20, null=True)

EventHub/mysite/news/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


#added comment
class NewUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms. EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

EventHub/mysite/custom_app/views.py
from braces.views import LoginRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model


class UserListView(LoginRequiredMixin, generic.ListView):
    model = get_user_model()
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = 'custom_app/chat.html'
    login_url = 'admin/'

EventHub/mysite/news/templates/news/includes/messages.html
{% if messages %}
       {% for message in messages %}
           {% if message.tags == 'success'%}
               <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
           {% elif message.tags == 'info'%}
               <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
           {% elif message.tags == 'warning'%}
               <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
           {% elif message.tags == 'error'%}
               <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
           {% endif %}
       {% endfor %}
{% endif %}

EventHub/mysite/news/templates/news/includes/navbar.html
{% load static %}
<nav id="sidebar" style="height: 800px;">
  <div class="custom-menu">
    <button type="button" id="sidebarCollapse" class="btn btn-primary">
            </button>
          </div>
  <div class="img bg-wrap text-center py-4" style="background-image: url('{% static "navbar/images/bg_1.jpg" %}');">
    <div class="user-logo">
      <div class="img" style="background-image: url('{% static "navbar/images/logo.jpg" %}');"></div>
      <h3>{{user.username}}</h3>
    </div>
  </div>
      <ul class="list-unstyled components mb-5">
        <li class="active">
           <a href="{% url 'news:userhome' %}"><span class="fa fa-home mr-3"></span> Home</a>
        </li>
        <li>
           <a href="{% url 'news:usermap' %}"><span class="fa fa-download mr-3 notif"><small class="d-flex align-items-center justify-content-center"></small></span> Map</a>
        </li>
        <li>
            <a href="#"><span class="fa fa-gift mr-3"></span> News</a>
        </li>
        <li>
          <a href="#"><span class="fa fa-trophy mr-3"></span> Report</a>
        </li>
        <li>
          <a href="/logout"><span class="fa fa-sign-out mr-3"></span> Sign Out</a>
        </li>
      </ul>

 </nav>